<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUgPfUgT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUgPfUgT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUgPfUgT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUgPfUgT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUgPfUgT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UgPfUgT',
    'container.build_id' => '3ab8468b',
    'container.build_time' => 1737840417,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUgPfUgT');
