<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'app_centre_index' => [[], ['_controller' => 'App\\Controller\\CentreController::index'], [], [['text', '/centre/']], [], []],
    'app_centre_new' => [[], ['_controller' => 'App\\Controller\\CentreController::new'], [], [['text', '/centre/new']], [], []],
    'app_centre_show' => [['id'], ['_controller' => 'App\\Controller\\CentreController::show'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/centre']], [], []],
    'app_centre_edit' => [['id'], ['_controller' => 'App\\Controller\\CentreController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id'], ['text', '/centre']], [], []],
    'app_centre_delete' => [['id'], ['_controller' => 'App\\Controller\\CentreController::delete'], [], [['variable', '/', '[^/]++', 'id'], ['text', '/centre']], [], []],
    'ej1' => [[], ['_controller' => 'App\\Controller\\HomeController::ej1'], [], [['text', '/listarCentros']], [], []],
    'ej2' => [[], ['_controller' => 'App\\Controller\\HomeController::ej2'], [], [['text', '/centrosValencia']], [], []],
    'ej3' => [[], ['_controller' => 'App\\Controller\\HomeController::ej3'], [], [['text', '/ciclos']], [], []],
    'ej4' => [[], ['_controller' => 'App\\Controller\\HomeController::ej4'], [], [['text', '/centrosDAM']], [], []],
    'ej5' => [[], ['_controller' => 'App\\Controller\\HomeController::ej5'], [], [['text', '/centro18']], [], []],
    'ej6' => [[], ['_controller' => 'App\\Controller\\HomeController::ej6'], [], [['text', '/insertarCentro']], [], []],
    'ej7' => [[], ['_controller' => 'App\\Controller\\HomeController::ej7'], [], [['text', '/actualizarTelefono']], [], []],
    'ej8' => [[], ['_controller' => 'App\\Controller\\HomeController::ej8'], [], [['text', '/eliminarIESMAR']], [], []],
    'app_test' => [[], ['_controller' => 'App\\Controller\\TestController::index'], [], [['text', '/test']], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
];
